# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.3.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6.3.2-0.1.29.zip
